"""port_traffic_and_vlan_detail

Revision ID: 4b48e1053d0a
Revises: 0006
Create Date: 2026-03-22 14:18:45.020414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b48e1053d0a'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alarm_actions_alarm_id', table_name='alarm_actions')
    op.drop_constraint('alarm_actions_alarm_id_fkey', 'alarm_actions', type_='foreignkey')
    op.create_foreign_key(None, 'alarm_actions', 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')
    op.alter_column('alarms', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_alarms_device_id', table_name='alarms')
    op.drop_index('ix_alarms_status', table_name='alarms')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_buildings_site_id', table_name='buildings')
    op.add_column('device_ports', sa.Column('admin_status', sa.String(length=16), nullable=True))
    op.add_column('device_ports', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('device_ports', sa.Column('port_type', sa.String(length=64), nullable=True))
    op.add_column('device_ports', sa.Column('vlan_mode', sa.String(length=16), nullable=True))
    op.add_column('device_ports', sa.Column('pvid', sa.String(length=16), nullable=True))
    op.add_column('device_ports', sa.Column('tagged_vlans', sa.String(length=512), nullable=True))
    op.add_column('device_ports', sa.Column('rx_bytes', sa.BigInteger(), nullable=True))
    op.add_column('device_ports', sa.Column('tx_bytes', sa.BigInteger(), nullable=True))
    op.add_column('device_ports', sa.Column('traffic_in_bps', sa.Float(), nullable=True))
    op.add_column('device_ports', sa.Column('traffic_out_bps', sa.Float(), nullable=True))
    op.alter_column('device_ports', 'port_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_index('ix_device_ports_device_id', table_name='device_ports')
    op.drop_index('ix_devices_building_id', table_name='devices')
    op.drop_index('ix_devices_consecutive_failures', table_name='devices')
    op.drop_index('ix_devices_site_id', table_name='devices')
    op.drop_index('ix_devices_status', table_name='devices')
    op.drop_index('ix_endpoints_device_id', table_name='endpoints')
    op.drop_index('ix_sites_group_id', table_name='sites')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_virtual_devices_model_id', table_name='virtual_devices')
    op.drop_constraint('virtual_devices_model_id_fkey', 'virtual_devices', type_='foreignkey')
    op.create_foreign_key(None, 'virtual_devices', 'device_models', ['model_id'], ['id'])
    op.drop_index('ix_vlans_device_id', table_name='vlans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vlans_device_id', 'vlans', ['device_id'], unique=False)
    op.drop_constraint(None, 'virtual_devices', type_='foreignkey')
    op.create_foreign_key('virtual_devices_model_id_fkey', 'virtual_devices', 'device_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_virtual_devices_model_id', 'virtual_devices', ['model_id'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_index('ix_sites_group_id', 'sites', ['group_id'], unique=False)
    op.create_index('ix_endpoints_device_id', 'endpoints', ['device_id'], unique=False)
    op.create_index('ix_devices_status', 'devices', ['status'], unique=False)
    op.create_index('ix_devices_site_id', 'devices', ['site_id'], unique=False)
    op.create_index('ix_devices_consecutive_failures', 'devices', ['consecutive_failures'], unique=False)
    op.create_index('ix_devices_building_id', 'devices', ['building_id'], unique=False)
    op.create_index('ix_device_ports_device_id', 'device_ports', ['device_id'], unique=False)
    op.alter_column('device_ports', 'port_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.drop_column('device_ports', 'traffic_out_bps')
    op.drop_column('device_ports', 'traffic_in_bps')
    op.drop_column('device_ports', 'tx_bytes')
    op.drop_column('device_ports', 'rx_bytes')
    op.drop_column('device_ports', 'tagged_vlans')
    op.drop_column('device_ports', 'pvid')
    op.drop_column('device_ports', 'vlan_mode')
    op.drop_column('device_ports', 'port_type')
    op.drop_column('device_ports', 'description')
    op.drop_column('device_ports', 'admin_status')
    op.create_index('ix_buildings_site_id', 'buildings', ['site_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_alarms_status', 'alarms', ['status'], unique=False)
    op.create_index('ix_alarms_device_id', 'alarms', ['device_id'], unique=False)
    op.alter_column('alarms', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'alarm_actions', type_='foreignkey')
    op.create_foreign_key('alarm_actions_alarm_id_fkey', 'alarm_actions', 'alarms', ['alarm_id'], ['id'])
    op.create_index('ix_alarm_actions_alarm_id', 'alarm_actions', ['alarm_id'], unique=False)
    # ### end Alembic commands ###
