"""add_container_ip_to_virtual_devices

Revision ID: 9b7dc8d8b529
Revises: 4b48e1053d0a
Create Date: 2026-03-22 14:34:14.845509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7dc8d8b529'
down_revision: Union[str, None] = '4b48e1053d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_devices', sa.Column('container_ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_devices', 'container_ip')
    # ### end Alembic commands ###
